# Generated by Django 3.2.2 on 2021-05-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishing_year',
            field=models.IntegerField(default=2500),
        ),
    ]
