# Generated by Django 3.2.2 on 2021-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_publishing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
